name: Continuous Integration

on:
  pull_request:
  merge_group:
  push:
    branches: [huanchengchang/jstz-289]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  test:
    name: Test
    uses: huancheng-trili/jstz/.github/workflows/cli-npm.yaml@huanchengchang/jstz-289
    with:
      dry_run: false
    secrets: inherit
