name: Continuous Integration

on:
  pull_request:
  merge_group:
  push:
    branches: [huanchengchang/jstz-932-test]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  run:
    uses: .github/workflows/docker-multiplatform.yml@huanchengchang/jstz-932-test
    with:
      ref: huanchengchang/jstz-932-test
      dry_run: false
    secrets: inherit
